# workflow that tests and quality-checks app on pull requests
name: Test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install packages
        run: yarn install
      - name: Test that app can build without issues
        run: yarn build
      - name: Run lint/formatting tests
        run: yarn lint
      - name: Run unit tests
        run: yarn test:unit
      - name: Run e2e/integration tests
        run: yarn test:e2e
      - name: Run accessibility tests
        run: yarn test:accessibility
